name: Dependabot CI & Auto-Merge

on:
  pull_request:

jobs:
  build:
    if: github.actor == 'dependabot[bot]'
    uses: preprio/.github/.github/workflows/node-build.yml@main
    with:
      node-version: "20"
      package-manager: "npm"
      build-command: "npm run build"
      run-tests: false

  composer-build:
    if: github.actor == 'dependabot[bot]'
    uses: preprio/.github/.github/workflows/composer-build.yml@main
    with:
      php-version: "8.2"
      run-tests: true
      test-command: "vendor/bin/phpunit"

  auto-merge:
    needs: [build, composer-build]
    if: github.actor == 'dependabot[bot]'
    uses: preprio/.github/.github/workflows/dependabot-auto-merge.yml@main
    secrets: inherit
